{
  "compatibility_date": "2025-11-08",
  "name": "asociacion-basket",
  "main": "src/index.js",
  "rules": [
    {
      "type": "CompiledContentType",
      "globs": ["**/*.html"],
      "fallthrough": true
    }
  ]
}
